name: .NET Core

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'README.md'
      - '**.jpg'

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      if: matrix.os == 'ubuntu-latest'
      run: dotnet pack --configuration Release
    - name: Upload Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: Diverse/bin/Release/*.nupkg
    - name: Upload nupkg to GitHub Release
      if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')
      run: gh release upload ${{ github.ref_name }} Diverse/bin/Release/*.nupkg
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
